[profile.default]
libs = ['lib']
solc = '0.8.19'
remappings = [
    '@openzeppelin-contracts=lib/openzeppelin-contracts/'
]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config